---
title: "Seurat vs CELESTA"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: hide
    df_print: paged 
    geometry: margin=2cm
    highlight: textmate
    theme: journal
    fig_crop: false
    toc: true
    toc_float: true
  pdf_document: default
---
<style type="text/css">
.main-container {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(dplyr)
library(ggplot2)
library(kableExtra)
```


```{r}
celesta_class_file <- list.files('.', pattern = "^celesta_classes_.*.csv", full.names = T)
seurat_cluster_file <- list.files('.', pattern = "^seurat_clusters_.*.csv", full.names = T)

roi <- sub("celesta_classes_", "", tools::file_path_sans_ext(basename(celesta_class_file)))

celesta_classes <- fread(celesta_class_file)
seurat_clusters <- fread(seurat_cluster_file)

seurat_clusters <- seurat_clusters %>% filter(seurat_clusters != "Artifact")

clusters_joined <- inner_join(celesta_classes, seurat_clusters, by = c("x" = "x", "y" = "y"))

clusters_out <- clusters_joined %>% select(x, y, celesta_celltype = `Final cell type`, seurat_clusters)
fwrite(clusters_out, paste0("seurat_vs_celesta_clusters_", roi, ".csv"))
```

## `r roi`

```{r}
table(clusters_joined$`Final cell type`, clusters_joined$seurat_clusters) %>%
  kbl() %>%
  kable_styling()
```



```{r}
compare_tab <- data.frame(table(clusters_joined$`Final cell type`, clusters_joined$seurat_clusters))
colnames(compare_tab) <- c("CELESTA prediction", "Seurat cluster", "Freq")

p <- ggplot(compare_tab, aes(x = `CELESTA prediction`, y = Freq, fill = `Seurat cluster`)) +
  geom_bar(position="fill", stat="identity") +
  xlab("CELESTA prediction") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
plot(p)
```



```{r}
clusters_joined$`Final cell type`[clusters_joined$`Final cell type` == "Unknown"] <- NA

## Plot CELESTA cell types
p1 <- ggplot(clusters_joined %>% arrange(desc(is.na(clusters_joined$`Final cell type`))), aes(x = x, y = y, color = `Final cell type`)) +
  geom_point() +
  scale_y_reverse() +
  coord_fixed() +
  theme_bw() +
  scale_color_discrete(na.value = "gray80") +
  ggtitle("CELESTA")
```

```{r fig.width=12, fig.height=6}
## Plot Seurat clusters
clusters_joined$seurat_clusters <- factor(clusters_joined$seurat_clusters, levels = paste0("cluster_", 0:length(unique(clusters_joined$seurat_clusters)) -1))

p2 <- ggplot(clusters_joined, aes(x = x, y = y, color = seurat_clusters)) +
  geom_point() +
  scale_y_reverse() +
  coord_fixed() +
  theme_bw() +
  scale_color_discrete(na.value = "gray80") +
  ggtitle("Seurat")

plot(p1)

plot(p2)
```



























